/**
 * S3 — OscillateAndGenerate
 *
 * Generate structurally independent perspectives on a problem.
 * Multiple agents produce framings from different vantage points.
 *
 * Sub-agent policy: MUST fan out to sub-agents. Each perspective is
 * generated by a separate sub-agent in isolation. Perspectives that
 * share assumptions are partially redundant and reduce signal
 * extraction quality.
 *
 * [Source: G1 - redundancy across independent measurements separates
 * signal from noise]
 */

import type {
  OscillateInput,
  OscillateOutput,
  Framing,
  LensAssignment,
  IndependenceCheckResult,
  PairwiseComparison,
  ReflectOutput,
} from "./types.ts";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const MIN_AGENTS = 2;
const MAX_AGENTS = 4;

// ---------------------------------------------------------------------------
// Core Oscillate function
// ---------------------------------------------------------------------------

/**
 * OscillateAndGenerate: fan out to 2-4 sub-agents in isolation.
 *
 * Each Perspective Agent receives:
 * - The problem statement
 * - A single lens assignment
 * - Seed material from prior Reflect output (if available)
 *
 * Agents operate in ISOLATION — they do NOT see each other's output
 * during generation.
 *
 * After all agents complete, an independence check compares
 * foundational assumptions across agent pairs.
 */
export function oscillateAndGenerate(input: OscillateInput): OscillateOutput {
  validateInput(input);

  // Fan out: each lens assignment produces one framing in isolation
  const framings = fanOutToAgents(
    input.problemStatement,
    input.lensAssignments,
    input.seedMaterial,
  );

  // Post-generation: check independence across all agent pairs
  const independenceCheck = checkIndependence(framings);

  return {
    framings,
    independenceCheck,
    agentCount: framings.length,
  };
}

// ---------------------------------------------------------------------------
// Fan-out: 2-4 sub-agents in isolation
// ---------------------------------------------------------------------------

/**
 * Spawns 2-4 Perspective Agent sub-agents. Each agent operates in
 * isolation — it receives only its own lens, the problem statement,
 * and optional seed material. It does NOT see other agents' output.
 */
function fanOutToAgents(
  problemStatement: string,
  lensAssignments: LensAssignment[],
  seedMaterial: ReflectOutput | null,
): Framing[] {
  // Each agent generates its framing independently
  // In production, these run as parallel sub-agents via S6
  const framings: Framing[] = lensAssignments.map((lens) =>
    generateFramingInIsolation(problemStatement, lens, seedMaterial),
  );

  return framings;
}

/**
 * A single Perspective Agent generates a framing in isolation.
 * This is the unit of work that runs as a sub-agent.
 */
function generateFramingInIsolation(
  problemStatement: string,
  lens: LensAssignment,
  seedMaterial: ReflectOutput | null,
): Framing {
  // Seed material from prior Reflect enriches the perspective
  const seedContext = seedMaterial
    ? buildSeedContext(seedMaterial)
    : "";

  return {
    perspectiveId: lens.perspectiveId,
    lens,
    content: [
      `Problem: ${problemStatement}`,
      `Perspective: ${lens.domain} / ${lens.stakeholder}`,
      `Time Horizon: ${lens.timeHorizon}`,
      `Abstraction: ${lens.abstractionLevel}`,
      seedContext,
    ]
      .filter(Boolean)
      .join("\n"),
    foundationalAssumptions: [],
  };
}

/**
 * Build seed context from prior Reflect output for lens enrichment.
 * This is the closed-loop mechanism: Reflect -> Oscillate.
 */
function buildSeedContext(reflectOutput: ReflectOutput): string {
  const parts: string[] = [];

  if (reflectOutput.seedForNextCycle.frameworkDelta) {
    parts.push(`Framework delta: ${reflectOutput.seedForNextCycle.frameworkDelta}`);
  }

  if (reflectOutput.seedForNextCycle.motifCandidates.length > 0) {
    const motifNames = reflectOutput.seedForNextCycle.motifCandidates
      .map((m) => m.name)
      .join(", ");
    parts.push(`Prior motif candidates: ${motifNames}`);
  }

  if (reflectOutput.seedForNextCycle.processObservations.length > 0) {
    parts.push(
      `Process observations: ${reflectOutput.seedForNextCycle.processObservations.join("; ")}`,
    );
  }

  return parts.length > 0 ? `[Seed from prior Reflect]\n${parts.join("\n")}` : "";
}

// ---------------------------------------------------------------------------
// Independence check: compare foundational assumptions across pairs
// ---------------------------------------------------------------------------

/**
 * Compare foundational assumptions across all agent pairs.
 * High overlap indicates partially redundant perspectives.
 */
function checkIndependence(framings: Framing[]): IndependenceCheckResult {
  const pairwiseComparisons: PairwiseComparison[] = [];
  const redundancyFlags: string[] = [];

  // Compare every pair of agents
  for (let i = 0; i < framings.length; i++) {
    for (let j = i + 1; j < framings.length; j++) {
      const agentA = framings[i];
      const agentB = framings[j];

      const sharedAssumptions = findSharedAssumptions(
        agentA.foundationalAssumptions,
        agentB.foundationalAssumptions,
      );

      const totalUnique = new Set([
        ...agentA.foundationalAssumptions,
        ...agentB.foundationalAssumptions,
      ]).size;

      const independenceScore =
        totalUnique > 0
          ? 1.0 - sharedAssumptions.length / totalUnique
          : 1.0;

      pairwiseComparisons.push({
        agentA: agentA.perspectiveId,
        agentB: agentB.perspectiveId,
        sharedAssumptions,
        independenceScore,
      });

      if (independenceScore < 0.5) {
        redundancyFlags.push(
          `Agents ${agentA.perspectiveId} and ${agentB.perspectiveId} share >50% assumptions`,
        );
      }
    }
  }

  const overallScore =
    pairwiseComparisons.length > 0
      ? pairwiseComparisons.reduce((sum, c) => sum + c.independenceScore, 0) /
        pairwiseComparisons.length
      : 1.0;

  return {
    pairwiseComparisons,
    overallScore,
    redundancyFlags,
  };
}

/**
 * Find assumptions shared between two agents.
 */
function findSharedAssumptions(
  assumptionsA: string[],
  assumptionsB: string[],
): string[] {
  const setB = new Set(assumptionsB);
  return assumptionsA.filter((a) => setB.has(a));
}

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

function validateInput(input: OscillateInput): void {
  const count = input.lensAssignments.length;
  if (count < MIN_AGENTS || count > MAX_AGENTS) {
    throw new Error(
      `OscillateAndGenerate requires ${MIN_AGENTS}-${MAX_AGENTS} lens assignments, got ${count}`,
    );
  }

  if (!input.problemStatement.trim()) {
    throw new Error("OscillateAndGenerate requires a non-empty problem statement");
  }
}
