import { Command } from 'commander';
import { SearchIndex } from '../store/index';
import { VaultStore } from '../store/vault';

const BASE_DIR = process.cwd();
const DB_PATH = `${BASE_DIR}/.ocp/index.db`;

export const inspectCommand = new Command('inspect')
  .description('View a single Solution Record in detail')
  .argument('<record-id>', 'Record ID (e.g., ocp:github/owner--repo)')
  .option('--json', 'Output raw JSON-LD')
  .action((recordId: string, opts) => {
    // Try index first, fall back to vault
    const index = new SearchIndex(DB_PATH);
    let record = index.getRecord(recordId);
    index.close();

    if (!record) {
      const vault = new VaultStore(BASE_DIR);
      record = vault.load(recordId);
    }

    if (!record) {
      console.error(`\n❌ Record not found: ${recordId}`);
      console.error('   Use "ocp search" to find record IDs.\n');
      process.exit(1);
    }

    if (opts.json) {
      console.log(JSON.stringify(record, null, 2));
      return;
    }

    // Pretty print
    console.log(`\n═══ Solution Record ═══\n`);
    console.log(`  ID:     ${record['@id']}`);
    console.log(`  Title:  ${record.meta.title}`);
    console.log(`  Desc:   ${record.meta.description}`);
    console.log(`  Version: ${record.meta.version}`);
    if (record.meta.license) console.log(`  License: ${record.meta.license}`);
    if (record.meta.keywords?.length) console.log(`  Tags:   ${record.meta.keywords.join(', ')}`);

    console.log(`\n  ─── Problem Solved ───`);
    console.log(`  Statement: ${record.problemSolved.statement}`);
    if (record.problemSolved.context) console.log(`  Context:   ${record.problemSolved.context.slice(0, 200)}`);
    console.log(`  Cynefin:   ${record.problemSolved.cynefinDomain}`);

    console.log(`\n  ─── Domains ───`);
    console.log(`  ${record.domains.join(', ')}`);

    console.log(`\n  ─── Validation ───`);
    console.log(`  Method: ${record.validation.method}`);
    for (const ev of record.validation.evidence) {
      console.log(`  Evidence: [${ev.type}] ${ev.description}`);
    }

    console.log(`\n  ─── Implementation ───`);
    console.log(`  Type: ${record.implementation.type}`);
    if (record.implementation.language) console.log(`  Language: ${record.implementation.language}`);
    for (const ref of record.implementation.refs) {
      console.log(`  Ref: [${ref.type}] ${ref.uri}`);
    }

    console.log(`\n  ─── Composability ───`);
    const runtimeDeps = record.composability.dependencies.filter(d => d.type === 'runtime');
    console.log(`  Dependencies: ${runtimeDeps.length} runtime`);
    for (const dep of runtimeDeps.slice(0, 10)) {
      console.log(`    ${dep.name}${dep.version ? '@' + dep.version : ''}`);
    }
    if (runtimeDeps.length > 10) console.log(`    ... and ${runtimeDeps.length - 10} more`);

    console.log(`\n  ─── Provenance ───`);
    console.log(`  Source: ${record.provenance.sourceType}`);
    console.log(`  Authors: ${record.provenance.authors.map(a => a.name).join(', ')}`);
    if (record.provenance.generatedBy) console.log(`  Generated by: ${record.provenance.generatedBy}`);

    console.log(`\n  ─── Trust ───`);
    console.log(`  Score:      ${record.trust.trustScore?.toFixed(3) || 'N/A'}`);
    console.log(`  Confidence: ${record.trust.confidence}`);
    console.log(`  Authority:  ${record.trust.authority}`);
    console.log(`  Status:     ${record.trust.status}`);
    const v = record.trust.vector;
    console.log(`  Vector:`);
    console.log(`    validation_count:      ${v.validation_count}`);
    console.log(`    validation_diversity:   ${v.validation_diversity}`);
    console.log(`    context_breadth:        ${v.context_breadth}`);
    console.log(`    temporal_stability:     ${v.temporal_stability}`);
    console.log(`    test_coverage:          ${v.test_coverage}`);
    console.log(`    documentation_quality:  ${v.documentation_quality}`);

    console.log('');
  });
