// S0: Barrel export — all types, schemas, errors, and IDs

// Types (pure type exports — no runtime cost)
export type {
  ClientType,
  ThreadStatus,
  IntentType,
  ItemType,
  ApprovalTier,
  AuditCategory,
  TaskType,
  SensitivityLevel,
  BackendHealthState,
  Session,
  Thread,
  Turn,
  Attachment,
  PolicyRequest,
  PolicyDecision,
  PolicyRule,
  PolicyCondition,
  ApprovalRequestParams,
  ApprovalResult,
  PendingApproval,
  ApprovalDecision,
  AuditEvent,
  AuditFilter,
  AuditQueryResult,
  ISCCriteria,
  DispatchRequest,
  DispatchResult,
  BackendStatus,
  HealthStatus,
  HealthChange,
  ObserverErrorData,
  SessionResumeResult,
  SessionCreateParams,
  SessionCreateResult,
  SessionCloseParams,
  SessionCloseResult,
  SessionResumeParams,
  ThreadCreateParams,
  ThreadCreateResult,
  ThreadStatusParams,
  ThreadStatusResult,
  ThreadCancelParams,
  ThreadCancelResult,
  TurnSubmitParams,
  TurnSubmitResult,
  ApprovalRespondParams,
  ApprovalRespondResult,
  HealthStatusParams,
  AuditQueryParams,
  AdminRevokeTokenParams,
  AdminRevokeTokenResult,
  // Service interfaces
  SessionManager,
  PolicyEnforcer,
  ApprovalGateway,
  AuditLogger,
  AuditStore,
  SessionStore,
  HealthMonitor,
} from "./types.js";

// Runtime values from types
export { ObserverErrorCode, ID_PREFIXES, ID_LENGTHS } from "./types.js";

// Schemas
export {
  ClientTypeSchema,
  ThreadStatusSchema,
  IntentTypeSchema,
  ItemTypeSchema,
  ApprovalTierSchema,
  AuditCategorySchema,
  TaskTypeSchema,
  SensitivityLevelSchema,
  BackendHealthStateSchema,
  AttachmentSchema,
  SessionSchema,
  ThreadSchema,
  TurnSchema,
  PolicyConditionSchema,
  PolicyRequestSchema,
  PolicyDecisionSchema,
  PolicyRuleSchema,
  ApprovalRequestParamsSchema,
  ApprovalResultSchema,
  PendingApprovalSchema,
  ApprovalDecisionSchema,
  AuditEventSchema,
  AuditFilterSchema,
  AuditQueryResultSchema,
  ISCCriteriaSchema,
  DispatchRequestSchema,
  DispatchResultSchema,
  BackendStatusSchema,
  HealthStatusSchema,
  HealthChangeSchema,
  ObserverErrorDataSchema,
  SessionResumeResultSchema,
  SessionCreateParamsSchema,
  SessionCreateResultSchema,
  SessionCloseParamsSchema,
  SessionCloseResultSchema,
  SessionResumeParamsSchema,
  ThreadCreateParamsSchema,
  ThreadCreateResultSchema,
  ThreadStatusParamsSchema,
  ThreadStatusResultSchema,
  ThreadCancelParamsSchema,
  ThreadCancelResultSchema,
  TurnSubmitParamsSchema,
  TurnSubmitResultSchema,
  ApprovalRespondParamsSchema,
  ApprovalRespondResultSchema,
  AuditQueryParamsSchema,
  AdminRevokeTokenParamsSchema,
  AdminRevokeTokenResultSchema,
} from "./schemas.js";

// Errors
export { createError, errorCodeName } from "./errors.js";
export type { JsonRpcError } from "./errors.js";

// ID generation
export { generateId, ALPHABET } from "./ids.js";
